# Server settings
server:
    port: 8080
    address: localhost
    compression:
        enabled: true
spring:
    http:
        converters:
            preferred-json-mapper: jackson
    datasource:
        name: hikariDataSource
        pool-name: hikari
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://rm-m5e85711k4p77t9c8.mysql.rds.aliyuncs.com:3306/dubei?allowMultiQueries=true
        username: dubei
        password: DuBei2017*#
        
        # hikari
        type: com.zaxxer.hikari.HikariDataSource
        maximum-pool-size: 5
        max-idle: 3
        max-wait: 10000
        min-idle: 1
        initial-size: 5
        validation-query: SELECT 1
        test-on-borrow: false
        test-while-idle: true
        time-between-eviction-runs-millis: 18800
    mvc:
        view:
            prefix: /WEB-INF/templates/
            suffix: .vm
        date-format: yyyy-MM-dd HH:mm:ss
        static-path-pattern: /static/**
    aop:
        proxy-target-class: true
    velocity:
        cache: false
        request-context-attribute: request
        number-tool-attribute: number
        date-tool-attribute: date
        resource-loader-path: /WEB-INF/templates/
    resources:
        static-locations: /static/
    redis:
        database: 0
        host: localhost
        password: 
        pool:
            max-active: 2
            max-idle: 2
            max-wait: -1
            min-idle: 1
            port: 6379
    jackson:
        date-format: yyyy-MM-dd
        serialization-inclusion: NON_NULL
        mapper: true
        timeZone: GMT+8

multipart:
    location: /temp
    file-size-threshold: 1048576
    max-file-size: 2097152
    max-request-size: 15728640

# MyBatis
mybatis:
    typeAliasesPackage: com.wechat.core.model
    mapperLocations: classpath:mapper/*.xml
    configLocation: classpath:conf/mybatis-config.xml     